CREATE TABLE IF NOT EXISTS tokens(
    user_id TEXT PRIMARY KEY,
    access_token TEXT UNIQUE NOT NULL,
    refresh_token TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS gambles(
    user_id TEXT PRIMARY KEY,
    points BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS spotify(
    id SERIAL PRIMARY KEY,
    token TEXT UNIQUE NOT NULL,
    refresh TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS firsts(
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    dt TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS mods(
    user_id TEXT PRIMARY KEY,
    flags INT NOT NULL DEFAULT 0
);
